#!/usr/bin/env python3
"""Regenerate COORD-REVIEW.md from the per-batch evidence files."""
import json, glob, os
# Runs before the skip-worked fix re-geocoded the same holds, so the same listing
# appears in several files. Keep the latest result per listing; counting the raw rows
# would inflate "worked" exactly the way OPEN-ITEMS.md's tallies inflated.
latest = {}
for f in sorted(glob.glob('/home/claude/audit-results/run_*.json')):
    for r in json.load(open(f)):
        latest[r['name']] = r
rows = sorted(latest.values(), key=lambda r: r['name'])
rev  = [r for r in rows if r['status'] == 'REVIEW']
far  = [r for r in rows if r['status'] == 'FAR']
hold = [r for r in rows if r['status'] == 'HOLD']
ok   = [r for r in rows if r['status'] == 'OK']

def clean(a): return (a or '').replace('\\u2014','—').replace('\\u2013','–')

L = []
L.append('# Coordinate audit — entries NOT auto-applied\n')
L.append('Regenerated by `mkreview.py` from the per-batch result files. Do not hand-edit;')
L.append('hand-maintained tallies in this repo have been wrong every time they were checked.\n')
L.append(f'Worked so far: **{len(rows)}** queue entries — '
         f'{len(ok)} applied, {len(rev)} review, {len(far)} far, {len(hold)} hold.\n')
L.append('\n## REVIEW — matched, but the geocode cannot locate it precisely\n')
L.append('The returned address matched what the listing displays, but the result carries no')
L.append('house number, so it is the *road\'s* representative point. Where the road is longer')
L.append('than ~800 m that point locates nothing, and the existing pin may well be the better')
L.append('one. **Never bulk-apply these.** Each needs the operator\'s own page or a map look.\n')
if rev:
    L.append('| Listing | Displayed address | Current pin | Geocode | Drift | Road extent |')
    L.append('|---|---|---|---|---|---|')
    for r in rev:
        ex = r.get('extent_km')
        L.append(f"| {r['name']} | {clean(r['addr'])}, {r['city']} {r['zipc']} | "
                 f"{r['cur'][0]}, {r['cur'][1]} | {r['new'][0]:.6f}, {r['new'][1]:.6f} | "
                 f"{r['km']:.2f} km | {('%.2f km' % ex) if ex else 'n/a'} |")
L.append('\n## FAR — matched but >25 km away, never auto-applied\n')
L.append('A jump this large is the Serendipity failure shape. Read before it moves.\n')
if far:
    for r in far:
        L.append(f"- **{r['name']}** — {clean(r['addr'])}, {r['city']}: "
                 f"{r['km']:.1f} km to {r['new'][0]:.6f}, {r['new'][1]:.6f}")
else:
    L.append('_None._\n')
L.append('\n## HOLD — no acceptable match\n')
L.append('Either the geocoder returned nothing, or every result disagreed with the address')
L.append('the listing displays. Grouped by why.\n')
REGION, NOTFOUND, MISMATCH = [], [], []
for r in hold:
    reasons = ' '.join(r.get('reasons', []))
    if 'mismatch' in reasons or 'rejected' in reasons: MISMATCH.append(r)
    elif any(k in clean(r['addr']).lower() for k in
             ['foothills','outside','coast','across','downtown','off i-','at the foot']):
        REGION.append(r)
    else: NOTFOUND.append(r)
for title, grp, note in [
    ('Region descriptions, not addresses', REGION,
     'These name an area. A coarse pin is honest here; the fix is `coord_scope:\'region\'` '
     'once each is confirmed, or the operator\'s exact address.'),
    ('Address disagrees with every result', MISMATCH,
     'The geocoder found something and it was refused. Read the reason before acting.'),
    ('Not in OpenStreetMap', NOTFOUND,
     'Rural roads, alleys and small-town cross streets are often simply absent. Needs the '
     'operator page or a second source.')]:
    L.append(f'\n### {title} ({len(grp)})\n')
    L.append(note + '\n')
    for r in grp:
        L.append(f"- **{r['name']}** — {clean(r['addr'])}, {r['city']} {r['zipc']}")
        why = (r.get('reasons') or ['—'])[-1]
        L.append(f"  - {why[:160]}")
open('COORD-REVIEW.md','w').write('\n'.join(L) + '\n')
print(f'wrote COORD-REVIEW.md: {len(rows)} worked, {len(ok)} ok, {len(rev)} review, {len(far)} far, {len(hold)} hold')
